name: Check eslint and prettier rules

on:
  push:
    branches:
      - develop
      - main

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
      - name: ESLint and Prettier Check
        run: |
          npx eslint . --fix
          npx prettier . --write
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          npm install
      - name: Run tests
        run: |
          npm test
